AIRLINE/AIRLINE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flights.urls")),
    path('users/', include("users.urls"))
]

AIRLINE/flights/urls.py
from django.urls import path
from . import views

app_name = "flights"
urlpatterns = [
    path("",views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

AIRLINE/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

AIRLINE/flights/models.py
from django.db import models

# PS C:\Users\user\Desktop\CS50\airline> python manage.py shell
# 7 objects imported automatically (use -v 2 for details).

# Ctrl click to launch VS Code Native REPL
# Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
# Type "help", "copyright", "credits" or "license" for more information.
# (InteractiveConsole)
# >>> from flights.models import Flight
# >>> f = Flight(origin="New York", destination="London", duration=415)
# >>> f.save()
# > Flight.objects.all()
# <QuerySet [<Flight: Flight object (1)>]>
#  flights = Flight.objects.all()
# >>> flights
# <QuerySet [<Flight: 1 New York to London>]>

# Ctrl click to launch VS Code Native REPL
# Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
# Type "help", "copyright", "credits" or "license" for more information.
# (InteractiveConsole)
# >>> jfk = Airport(code="JFK", city="New York")
# >>> jfk.save()
# >>> lhr = Airport(code="LHR", city="London 
#   File "<console>", line 1
#     lhr = Airport(code="LHR", city="London
#                                    ^
# SyntaxError: unterminated string literal (detected at line 1)
# >>> lhr = Airport(code="LHR", city="London"
# ... lhr = Airport(code="LHR", city="London")
#   File "<console>", line 1
#     lhr = Airport(code="LHR", city="London"
#                  ^
# SyntaxError: '(' was never closed
# >>> lhr = Airport(code="LHR", city="London")
# >>> lhr.save()
# >>> cdg = Airport(code="CDG",city="Paris")  
# >>> cdg.save()
# >>> nrt =(code="NRT", city="Tokyo")
#   File "<console>", line 1
#     nrt =(code="NRT", city="Tokyo")
#           ^^^^^^^^^^
# SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
# >>> nrt =Airport(code="NRT", city="Tokyo") 
# >>> nrt.save
# <bound method Model.save of <Airport: Tokyo (NRT)>>
# >>> nrt.save()
# >>> 
# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)
    
    def __str__(self):
        return f"{self.city} ({self.code})"
    
class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()
    
    def __str__(self):
        return f"{self.id} {self.origin} to {self.destination}"
    
class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")
    
    def __str__(self):
        return f"{self.first} {self.last}"
    

AIRLINE/users/models.py
from django.db import models

# Create your models here.

AIRLINE/flights/views.py
from django.shortcuts import render
from .models import Flight, Passenger
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
# class Passenger(forms.Form):
#     name = forms.CharField(max_length=64)
    
def index(request):
    return render(request, "flights/index.html",{
        "flights": Flight.objects.all()
    })
    
def flight(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    return render(request, "flights/flight.html",{
        "flight": flight,
        "passengers": flight.passengers.all(),
        "non_passengers": Passenger.objects.exclude(flights=flight).all()
    })
    
def book(request, flight_id):
    if request.method == 'POST':
        flight = Flight.objects.get(pk=flight_id)
        passenger = Passenger.objects.get(pk=int(request.POST["passenger"]))
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flight", args=(flight.id,)))

AIRLINE/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "users/user.html")

def login_view(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username,password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        
        else:
            return render(request, "users/login.html",{
                "message": "Invalid Login Credentials"
            })
            
            
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request, "users/login.html",{
        "message": "Logout Successful"
    })

AIRLINE/flights/templates/flights/flight.html
{% extends "flights/layout.html"%}
{%block title%} Flights {%endblock%}
{%block body%}
    <h1>Flight {{ flight.id }}</h1>
    <ul>
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination}}</li>
        <li>Duration: {{flight.duration}}</li>
    </ul>

    <h2>Passengers</h2>
    <ul>
        {% for passenger in passengers %}
        <li>{{passenger}}</li>
        {%empty%}
        <li>No Passengers</li>
        {%endfor%}
    </ul>

    <h2>Add Passenger</h2>
    <form action="{% url 'book' flight.id%}" method="post">
        {% csrf_token %}
        <select name="passenger" id="">
            {% for passenger in non_passengers %}
            <option value="{{ passenger.id }}">{{ passenger }}</option>
            {%endfor%}
        </select>
        <input type="submit">
    </form>
    <a href="{% url 'index' %}">Back to Flight List</a>
{%endblock%}

AIRLINE/flights/templates/flights/index.html
{% extends "flights/layout.html" %}
{%block title%}Flights{%endblock%}
{%block body%}

    <h1>flights</h1>
    <ul>
        {% for flight in flights %}
        
        <li>
            <a href="{%url 'flight' flight.id%}">Flight {{ flight.id}}: {{flight.origin}} to {{flight.destination}}</a>
        </li>
        {%endfor%}
    </ul>
{%endblock%}

AIRLINE/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{% endblock %}</title>
</head>
<body>
    {%block body%}
    {%endblock%}
</body>
</html>

AIRLINE/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>
<body>
    {% block body%}
    {% endblock %}
</body>
</html>

AIRLINE/users/templates/users/login.html
{% extends "users/layout.html" %}
{%block body%}
{%if message %}
<div>{{ message }}</div>
{% endif %}
<form action="{% url 'users:login'%}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username">
    <input type="password" name="password" id="" placeholder="Password">
    <input type="submit">
</form>
{%endblock%}

AIRLINE/users/templates/users/user.html
{% extends "users/layout.html"%}
{% block body %}
    <h1>Welcome, {{ request.user.first_name }} {{ request.user.last_name }}</h1>
    <ul>
        <li>Username: {{ request.user.username}}</li>
        <li>Email: {{ request.user.email}}</li>
    </ul>
    <a href="{% url 'users:logout'%}">Logout</a>

{% endblock %}